### ISSUE TITLE
baseFile is compulsory and can not get current folder name

### ISSUE THREAD

**Issue by harryjoy** [Charminbear/gulp-subdir-rename#1]
In my current situation, I am trying to rename bunch of directories and 99% of them contains baseFile but some exception modules does not contain that file. Right now rename task fails as it expects baseFile compulsory.

Also it would be better to provide current folder name as argument to renameTo function, if someone wants to just rename based on current name and does not want to have a baseFile. (That's what my case is)

In my requirement all folder names are like xzc@1.2.3 and i want to rename all to remove the version part (i.e. @1.2.3 part) from name.

**Comment by davelosert** [comment]
Hi, thanks for your issue.

if I understand you correctly: 
One task would be to not fail when there is no basefile but to simply ignore the folder. I agree that this seems to be a good way of handling that. You wanna send a PR for that?

And the second is to simply rename a folder matching a certain structure.
I wonder if  [gulp-rename](https://www.npmjs.com/package/gulp-rename) isn't the better option for that, used for example like this:

```
gulp.src("./src/**/*")
  .pipe(rename(function (path) {
    path.dirname = path.dirname.replace(/@[0-9]\.[0-9]\.[0-9]/gi, '');
  }))
```

I didn't test the above - but maybe it helps you?

**Comment by harryjoy** [comment]
Thanks for the response.

Yes, I ended up using gulp-rename with similar function and that works for me as of now. For that ignore part, I'll try to build and send a PR soon.

**Comment by harryjoy** [comment]
Implemented and added discussed PR.

**Comment by davelosert** [comment]
Closing this as I merged the PR.
