### ISSUE TITLE
Not deleting original folders

### ISSUE THREAD

**Issue by niC00L** [Charminbear/gulp-subdir-rename#3]
This plugin just copies folders to the same directory. Is it supposed to delete original folders as well? It would be great if it worked

**Comment by harryjoy** [comment]
Yes, you are right, currently, it does not remove folders, it renames them while copying to the destination. Also refer the issue listed in gulp-rename as well: https://github.com/hparra/gulp-rename/issues/34 . Similar idea here, I guess.

**Comment by davelosert** [comment]
Hi @niC00L :
Thanks for your message. 

as @harryjoy stated, this plugin is not intended to handle deletion - as there are already other and better plugins & ways to do it.

With [vinylPaths](https://github.com/gulpjs/gulp/blob/master/docs/recipes/delete-files-folder.md#delete-files-in-a-pipeline) it could look something like this:

```
gulp.task('copyAndDelete', function () {
  return gulp.src('sourceFolder/*')
    .pipe(vinylPaths(del))
    .pipe(subdirRename(options))
    .pipe(gulp.dest('targetFolder'));
});
```

Hope this helps. If you have any more questions or you disagree let me know!
